// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/access_token": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "request new access token.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/action-pipeline-status/{pipeline_id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "Action Pipeline"
                ],
                "summary": "Get the status of tools in given pipeline",
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "pipeline_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/change-password": {
            "patch": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "update the user password.",
                "parameters": [
                    {
                        "description": " ",
                        "name": "update_user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateUserDetails"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/create-pipeline": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "Action Pipeline"
                ],
                "summary": "Create a pipeline for currently selected tools",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/download-result-file": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "Action Pipeline"
                ],
                "summary": "Download the result file",
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "fileType",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/download-tool-generated-result-file": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "Action Pipeline"
                ],
                "summary": "get the Tool generated report files",
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "pipeline_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " ",
                        "name": "tool_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/email-result-file": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "Action Pipeline"
                ],
                "summary": "Email the generated result file",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/get-available-result": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "Action Pipeline"
                ],
                "summary": "Get the result of the given tool and pipeline",
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "pipeline_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " ",
                        "name": "tool_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/get_current_pipeline_configurations": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "User Tool Configuration"
                ],
                "summary": "Get all the current tool configurations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/get_verification_code": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Get verfication code on email.",
                "parameters": [
                    {
                        "description": " ",
                        "name": "verification_code",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GetVerificationCodeDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "User Login",
                "parameters": [
                    {
                        "description": " ",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/logout": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "Logout the user.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/metasploit_helper/options": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "User Tool Configuration"
                ],
                "summary": "Metasploit helper for options",
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "module_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": " ",
                        "name": "module_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/metasploit_helper/search": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "User Tool Configuration"
                ],
                "summary": "Metasploit helper for search",
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "search_field",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/reset_password": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Resetting the password when the user selects forget the password.",
                "parameters": [
                    {
                        "description": " ",
                        "name": "reset_password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ResetPasswordDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/run-pipeline": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "Action Pipeline"
                ],
                "summary": "start the created pipeline",
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "pipeline_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/save_tool_configuration/JMeterLoadTesting": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User Tool Configuration"
                ],
                "summary": "Save / Update the tool configuration",
                "parameters": [
                    {
                        "type": "string",
                        "name": "additional_comments",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "loop_count",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "loop_count_udf",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "number_of_threads",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "number_of_threads_udf",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "ramp_up_period",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "ramp_up_period_udf",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "enum": [
                            "PDF",
                            "HTML"
                        ],
                        "type": "string",
                        "name": "report_format",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "test_duration",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "test_duration_udf",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/save_tool_configuration/Metasploit": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User Tool Configuration"
                ],
                "summary": "Save / Update the tool configuration",
                "parameters": [
                    {
                        "description": " ",
                        "name": "Metasploit",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto_tool_configuration.MetasploitConfigurationDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/save_tool_configuration/Nmap": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User Tool Configuration"
                ],
                "summary": "Save / Update the tool configuration",
                "parameters": [
                    {
                        "description": " ",
                        "name": "Nmap",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto_tool_configuration.NmapConfigurationDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/save_tool_configuration/OWASPDependencyCheckDTO": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User Tool Configuration"
                ],
                "summary": "Save / Update the tool configuration",
                "parameters": [
                    {
                        "type": "string",
                        "name": "additional_comments",
                        "in": "formData"
                    },
                    {
                        "enum": [
                            "HTML",
                            "JSON",
                            "XML"
                        ],
                        "type": "string",
                        "name": "output_format",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "name": "scan_dependencies",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "name": "scan_dev_dependencies",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "name": "suppress_cve_reports",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "name": "suppress_update_check",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/save_tool_configuration/OWASPZAP": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User Tool Configuration"
                ],
                "summary": "Save / Update the tool configuration",
                "parameters": [
                    {
                        "description": " ",
                        "name": "Owasp_zap",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto_tool_configuration_zap.OWASPZAPConfigurationDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/save_tool_configuration/OpenVAS": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User Tool Configuration"
                ],
                "summary": "Save / Update the tool configuration",
                "parameters": [
                    {
                        "description": " ",
                        "name": "OpenVas",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto_tool_configuration.OpenVASConfigurationDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/save_tool_configuration/SQLMap": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User Tool Configuration"
                ],
                "summary": "Save / Update the tool configuration",
                "parameters": [
                    {
                        "description": " ",
                        "name": "SQLMap",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto_tool_configuration.SQLMapConfigurationDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/select-tools": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "Tool Selection"
                ],
                "summary": "Get the selected tools for the current session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "Tool Selection"
                ],
                "summary": "Select the tools for the current user session",
                "parameters": [
                    {
                        "description": " ",
                        "name": "select_tools",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SelectedToolsDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/tools": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "Tool Selection"
                ],
                "summary": "Get all the enabled tools.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/update_password": {
            "patch": {
                "tags": [
                    "User"
                ],
                "summary": "Updates the user password. Used internally by the reset password functionality.",
                "parameters": [
                    {
                        "description": " ",
                        "name": "update_password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdatePasswordDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/update_user_details": {
            "patch": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update the name and phone of the user.",
                "parameters": [
                    {
                        "description": " ",
                        "name": "update_user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateUserDetails"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get logged in user details.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "List of all registered users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Register User",
                "parameters": [
                    {
                        "description": " ",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreteNewUserDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "Find User By Id",
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "Delete User By Id",
                "parameters": [
                    {
                        "type": "string",
                        "description": " ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/verify_account": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Account verification post registration.",
                "parameters": [
                    {
                        "description": " ",
                        "name": "verify_account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.VerifyAccountDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CreteNewUserDTO": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password",
                "phone",
                "termsAcceptanceStatus"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "termsAcceptanceStatus": {
                    "type": "boolean"
                }
            }
        },
        "dto.GetVerificationCodeDTO": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "dto.ResetPasswordDTO": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "dto.SelectedToolsDTO": {
            "type": "object",
            "required": [
                "tool_ids"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "tool_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.UpdatePasswordDTO": {
            "type": "object",
            "required": [
                "password",
                "token"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateUserDetails": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "dto.UserDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.VerifyAccountDTO": {
            "type": "object",
            "required": [
                "code",
                "email"
            ],
            "properties": {
                "code": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                }
            }
        },
        "dto_tool_configuration.MetasploitConfigurationDTO": {
            "type": "object",
            "required": [
                "module_data",
                "module_fullname",
                "module_type"
            ],
            "properties": {
                "additional_comments": {
                    "type": "string"
                },
                "advanced_options": {
                    "type": "boolean"
                },
                "module_data": {},
                "module_fullname": {
                    "type": "string"
                },
                "module_type": {
                    "type": "string",
                    "enum": [
                        "auxiliary",
                        "encoder",
                        "evasion",
                        "exploit",
                        "nop",
                        "payload",
                        "post"
                    ]
                },
                "use_default_values": {
                    "type": "boolean"
                }
            }
        },
        "dto_tool_configuration.NmapConfigurationDTO": {
            "type": "object",
            "required": [
                "output_format",
                "port",
                "scan_timing",
                "scan_type",
                "target"
            ],
            "properties": {
                "aggressive_scan": {
                    "type": "boolean"
                },
                "default_nse_scripts": {
                    "type": "boolean"
                },
                "fragment_packets": {
                    "type": "boolean"
                },
                "max_retries": {
                    "type": "string"
                },
                "max_round_trip_timeout": {
                    "type": "string"
                },
                "output_format": {
                    "type": "string",
                    "enum": [
                        "XML",
                        "Normal",
                        "Grepable"
                    ]
                },
                "port": {
                    "type": "string"
                },
                "scan_all_ports": {
                    "type": "boolean"
                },
                "scan_timing": {
                    "type": "string",
                    "enum": [
                        "Slowest",
                        "Slow",
                        "Normal",
                        "Fast",
                        "Fastest"
                    ]
                },
                "scan_type": {
                    "type": "string",
                    "enum": [
                        "SYN Scan",
                        "TCP Connect Scan",
                        "UDP Scan",
                        "Comprehensive Scan"
                    ]
                },
                "script_scan": {
                    "type": "string",
                    "enum": [
                        "",
                        "None",
                        "Vulnerability Scripts",
                        "Default Scripts",
                        "Custom Scripts"
                    ]
                },
                "service_version_probe": {
                    "type": "boolean"
                },
                "show_port_state_reason": {
                    "type": "boolean"
                },
                "target": {
                    "type": "string"
                },
                "traceroute": {
                    "type": "boolean"
                },
                "version_detection_intensity": {
                    "type": "string",
                    "enum": [
                        "",
                        "Low",
                        "Medium",
                        "High"
                    ]
                }
            }
        },
        "dto_tool_configuration.OpenVASConfigurationDTO": {
            "type": "object",
            "required": [
                "no_of_concurrent_nvt_per_host",
                "no_of_concurrent_scanned_host",
                "port_range",
                "report_format",
                "scan_config",
                "scanner_type",
                "target"
            ],
            "properties": {
                "additional_comments": {
                    "type": "string"
                },
                "no_of_concurrent_nvt_per_host": {
                    "type": "integer"
                },
                "no_of_concurrent_scanned_host": {
                    "type": "integer"
                },
                "port_range": {
                    "$ref": "#/definitions/dto_tool_configuration.PortRange"
                },
                "report_format": {
                    "type": "string",
                    "enum": [
                        "XML",
                        "PDF",
                        "TEXT"
                    ]
                },
                "scan_config": {
                    "type": "string",
                    "enum": [
                        "Base",
                        "Discovery",
                        "empty",
                        "Full and fast",
                        "Host Discovery",
                        "Log4Shell",
                        "System Discovery"
                    ]
                },
                "scanner_type": {
                    "type": "string",
                    "enum": [
                        "OpenVAS Default",
                        "CVE"
                    ]
                },
                "target": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto_tool_configuration.PortRange": {
            "type": "object",
            "required": [
                "tcp",
                "udp"
            ],
            "properties": {
                "tcp": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "udp": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto_tool_configuration.SQLMapConfigurationDTO": {
            "type": "object",
            "required": [
                "number_of_threads",
                "report_format",
                "target",
                "testing_level",
                "testing_mode",
                "verbosity_level"
            ],
            "properties": {
                "additional_comments": {
                    "type": "string"
                },
                "check_for_additional_urls": {
                    "type": "boolean"
                },
                "cookies": {
                    "type": "string"
                },
                "current_database": {
                    "type": "boolean"
                },
                "current_session_user": {
                    "type": "boolean"
                },
                "data": {
                    "type": "string"
                },
                "enumerate_columns": {
                    "type": "boolean"
                },
                "enumerate_databases": {
                    "type": "boolean"
                },
                "enumerate_passwords": {
                    "type": "boolean"
                },
                "enumerate_privileges": {
                    "type": "boolean"
                },
                "enumerate_roles": {
                    "type": "boolean"
                },
                "enumerate_schemas": {
                    "type": "boolean"
                },
                "enumerate_tables": {
                    "type": "boolean"
                },
                "enumerate_users": {
                    "type": "boolean"
                },
                "exclude_system_databases": {
                    "type": "boolean"
                },
                "headers": {
                    "type": "string"
                },
                "number_of_threads": {
                    "type": "string",
                    "enum": [
                        "Low",
                        "Medium",
                        "High"
                    ]
                },
                "report_format": {
                    "type": "string",
                    "enum": [
                        "PDF",
                        "TXT"
                    ]
                },
                "target": {
                    "type": "string"
                },
                "test_forms": {
                    "type": "boolean"
                },
                "testing_level": {
                    "type": "string",
                    "enum": [
                        "Level 1",
                        "Level 2",
                        "Level 3",
                        "Level 4",
                        "Level 5"
                    ]
                },
                "testing_mode": {
                    "type": "string",
                    "enum": [
                        "Automatic",
                        "Manual"
                    ]
                },
                "user_agent": {
                    "type": "string"
                },
                "verbosity_level": {
                    "type": "string",
                    "enum": [
                        "Level 0",
                        "Level 1",
                        "Level 2",
                        "Level 3",
                        "Level 4",
                        "Level 5",
                        "Level 6"
                    ]
                }
            }
        },
        "dto_tool_configuration_zap.OWASPZAPConfigurationDTO": {
            "type": "object",
            "required": [
                "attack_mode",
                "policy_template",
                "report_format",
                "scan_type",
                "target"
            ],
            "properties": {
                "additional_comments": {
                    "type": "string"
                },
                "attack_mode": {
                    "type": "string",
                    "enum": [
                        "Safe Mode",
                        "Standard Mode",
                        "Protected Mode",
                        "Attack Mode"
                    ]
                },
                "authentication": {
                    "type": "boolean"
                },
                "logged_in_indicator": {
                    "type": "string"
                },
                "login_url": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "password_parameter": {
                    "type": "string"
                },
                "policy_template": {
                    "type": "string",
                    "enum": [
                        "Low",
                        "Medium",
                        "High"
                    ]
                },
                "report_format": {
                    "type": "string",
                    "enum": [
                        "PDF",
                        "HTML"
                    ]
                },
                "scan_type": {
                    "type": "string",
                    "enum": [
                        "Passive Scan",
                        "Active Scan"
                    ]
                },
                "spider_type": {
                    "type": "string",
                    "enum": [
                        "Traditional Spider",
                        "Ajax Spider"
                    ]
                },
                "target": {
                    "type": "string"
                },
                "traditional_spider_options": {
                    "$ref": "#/definitions/dto_tool_configuration_zap.TraditionalSPiderOptions"
                },
                "username": {
                    "type": "string"
                },
                "username_parameter": {
                    "type": "string"
                }
            }
        },
        "dto_tool_configuration_zap.TraditionalSPiderOptions": {
            "type": "object",
            "properties": {
                "max_children": {
                    "type": "integer"
                },
                "recurse": {
                    "type": "boolean"
                },
                "sub_tree_only": {
                    "type": "boolean"
                }
            }
        },
        "multipart.FileHeader": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string"
                },
                "header": {
                    "$ref": "#/definitions/textproto.MIMEHeader"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "textproto.MIMEHeader": {
            "type": "object",
            "additionalProperties": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            }
        },
        "utils.ApiResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {},
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Zplus Backend API",
	Description:      "API application for zplus security tool.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
