import os

TOOL_NAME_JMETER = "JMeterLoadTesting"
TOOL_NAME_METASPLOIT = "Metasploit"
TOOL_NAME_NMAP = "Nmap"
TOOL_NAME_OPENVAS = "OpenVAS"
TOOL_NAME_OWASPDEPENDENCY = "OWASPDependencyCheck"
TOOL_NAME_OWASPZAP = "OWASPZAP"
TOOL_NAME_SQLMAP = "SQLMap"

RMQ_NMAP_TASK_CONFIGURATIONS_QUEUE_NAME = "nmap_task_configuration_queue"
RMQ_METASPLOIT_TASK_CONFIGURATIONS_QUEUE_NAME = "metasploit_task_configuration_queue"
RMQ_OPENVAS_TASK_CONFIGURATIONS_QUEUE_NAME = "openvas_task_configuration_queue"
RMQ_OWASPZAP_TASK_CONFIGURATIONS_QUEUE_NAME = "owaspzap_task_configuration_queue"
RMQ_OWASPDEPENDENCY_TASK_CONFIGURATIONS_QUEUE_NAME = "owaspdependncy_check_task_configuration_queue"
RMQ_SQLMAP_TASK_CONFIGURATIONS_QUEUE_NAME = "sqlmap_task_configuration_queue"
RMQ_JMETER_TASK_CONFIGURATIONS_QUEUE_NAME = "jmeter_task_configuration_queue"

TOOL_PROCESSING_PENDING = "PENDING"
TOOL_PROCESSING_IN_PROGRESS = "IN-PROGRESS"
TOOL_PROCESSING_COMPLETED = "COMPLETED"
TOOL_PROCESSING_FAILED = "FAILED"

SECURITY_TOOL_INPUTS_FOLDER = "/security_tool_volume/inputs"
SECURITY_TOOL_RESULTS_FOLDER = "/security_tool_volume/results"
SECURITY_TOOL_HELPER_FOLDER = "/security_tool_volume/helper"


# Nmap constants
NMAP_START_COMMAND = "nmap"
CONTAINER_NMAP = "security_tool_container"
NMAP_CUSTOM_SCRIPTS_FILE_PATH = f"{SECURITY_TOOL_INPUTS_FOLDER}/{TOOL_NAME_NMAP}"

# Owasp dependency check constants
OWASP_DEPENDENCY_CHECK_START_COMMAND = "./dependency-check/bin/dependency-check.sh"
CONTAINER_OWASP_DEPENDENCY_CHECK = "security_tool_container"

# Metasploit constants
CONTAINER_METASPLOIT = "security_tool_metasploit"

# Owasp Zap Constants
ZAP_SCAN_TYPE_PASSIVE = "PASSIVE"
ZAP_SCAN_TYPE_ACTIVE = "ACTIVE"

ZAP_SPIDER_TYPE_TRADITIONAL = "TRADITIONAL"
ZAP_SPIDER_TYPE_AJAX = "AJAX"

ZAP_ATTACK_MODE_SAFE = "safe"
ZAP_ATTACK_MODE_STANDARD = "standard"
ZAP_ATTACK_MODE_PROTECTED = "protect"
ZAP_ATTACK_MODE_ATTACK = "attack"

ZAP_REPORT_FORMAT_HTML = "traditional-html"
ZAP_REPORT_FORMAT_PDF = "traditional-pdf"
ZAP_REPORT_FORMAT_JSON = "traditional-json"


CONTAINER_SQLMAP="security_tool_container"
SQLMAP_TESTING_MODE_AUTOMATIC="automatic"
SQLMAP_TESTING_MODE_MANUAL="manual"

SQLMAP_TESTING_LEVEL_1=1
SQLMAP_TESTING_LEVEL_2=2
SQLMAP_TESTING_LEVEL_3=3
SQLMAP_TESTING_LEVEL_4=4
SQLMAP_TESTING_LEVEL_5=5

SQLMAP_VERBOSITY_LEVEL_0=0
SQLMAP_VERBOSITY_LEVEL_1=1
SQLMAP_VERBOSITY_LEVEL_2=2
SQLMAP_VERBOSITY_LEVEL_3=3
SQLMAP_VERBOSITY_LEVEL_4=4
SQLMAP_VERBOSITY_LEVEL_5=5
SQLMAP_VERBOSITY_LEVEL_6=6


SQLMAP_NUMBER_OF_THREADS_LOW=2
SQLMAP_NUMBER_OF_THREADS_MEDIUM=5
SQLMAP_NUMBER_OF_THREADS_HIGH=10

SQLMAP_REPORT_FORMAT_PDF="PDF"
SQLMAP_REPORT_FORMAT_TEXT="TXT"


CONTAINER_JMETER = "security_tool_container"
JMETER_INPUTS_FOLDER="/security_tool_inputs/"+TOOL_NAME_JMETER
JMETER_LOGS_FOLDER="/security_tool_results/"+TOOL_NAME_JMETER+"/logs"
JMETER_REPORTS_FOLDER="/security_tool_results/"+TOOL_NAME_JMETER+"/reports"

JMETER_REPORT_FORMAT_HTML = "HTML"
JMETER_REPORT_FORMAT_PDF = "PDF"


PROJECT_ROOT_DIRECTORY=os.getenv("PROJECT_ROOT_DIRECTORY")


SECURITY_TOOL_VOLUME_ROOT_DIRECTORY=f"/security_tool_volume"
SECURITY_TOOL_ENGINE_INPUT_FOLDER=f"{SECURITY_TOOL_VOLUME_ROOT_DIRECTORY}/inputs"
SECURITY_TOOL_ENGINE_HELPER_FOLDER=f"{SECURITY_TOOL_VOLUME_ROOT_DIRECTORY}/helper"
SECURITY_TOOL_ENGINE_RESULTS_FOLDER=f"{SECURITY_TOOL_VOLUME_ROOT_DIRECTORY}/results"

SECURITY_TOOL_ENGINE_OPENVAS_SOCKET_FOLDER=f"{SECURITY_TOOL_VOLUME_ROOT_DIRECTORY}/openvas_socket"
SECURITY_TOOL_ENGINE_OWASP_ZAP_FOLDER=f"{SECURITY_TOOL_VOLUME_ROOT_DIRECTORY}/{TOOL_NAME_OWASPZAP}"

SECURITY_TOOL_ENGINE_NMAP_RESULTS_FOLDER=f"{SECURITY_TOOL_ENGINE_RESULTS_FOLDER}/{TOOL_NAME_NMAP}"
SECURITY_TOOL_ENGINE_OPENVAS_RESULTS_FOLDER=f"{SECURITY_TOOL_ENGINE_RESULTS_FOLDER}/{TOOL_NAME_OPENVAS}"

SECURITY_TOOL_ENGINE_OWASP_DEPENDENCY_CHECK_RESULTS_FOLDER=f"{SECURITY_TOOL_ENGINE_RESULTS_FOLDER}/{TOOL_NAME_OWASPDEPENDENCY}"

SECURITY_TOOL_ENGINE_SQLMAP_RESULTS_FOLDER=f"{SECURITY_TOOL_ENGINE_RESULTS_FOLDER}/{TOOL_NAME_SQLMAP}"
SECURITY_TOOL_ENGINE_METASPLOIT_RESULTS_FOLDER=f"{SECURITY_TOOL_ENGINE_RESULTS_FOLDER}/{TOOL_NAME_METASPLOIT}"

SECURITY_TOOL_ENGINE_JMETER_INPUTS_FOLDER=f"{SECURITY_TOOL_ENGINE_INPUT_FOLDER}/{TOOL_NAME_JMETER}"
SECURITY_TOOL_ENGINE_JMETER_LOGS_FOLDER=f"{SECURITY_TOOL_ENGINE_RESULTS_FOLDER}/{TOOL_NAME_JMETER}/logs"
SECURITY_TOOL_ENGINE_JMETER_REPORTS_FOLDER=f"{SECURITY_TOOL_ENGINE_RESULTS_FOLDER}/{TOOL_NAME_JMETER}/reports"

PWD=os.getcwd()
